version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network

  backend:
    image: sangwjdev/homeaid-backend:latest
    container_name: backend-app
    ports:
      - "8081:8080"  # 호스트포트:컨테이너포트 (Spring Boot 기본포트)
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    networks:
      - ci-network

volumes:
  jenkins_home:

networks:
  ci-network:
    driver: bridge
