# version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network

  backend:
    container_name: backend-app
    build:
      context: .
    ports:
      - "8081:8080"  # 호스트포트:컨테이너포트 (Spring Boot 기본포트)
    env_file:
      - dev.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_EXPIRE_TIME: ${ACCESS_TOKEN_EXPIRE_TIME}
      REFRESH_TOKEN_EXPIRE_TIME: ${REFRESH_TOKEN_EXPIRE_TIME}
    restart: always
    networks:
      - ci-network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: [ "redis-server", "--requirepass", "homeaidpassword" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ci-network
    restart: always

volumes:
  jenkins_home:

networks:
  ci-network:
    driver: bridge
