spring:
  application:
    name: HomeAid
  server:
    port: 8080

  profiles:
    active: local

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ${JWT_SECRET}

env:
  secure-cookie: false

springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: reservations
      packages-to-scan: com.homeaid.controller  # 실제 컨트롤러 패키지명!
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
