spring:
  application:
    name: HomeAid
  server:
    port: 8080

  profiles:
    active: local

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ${JWT_SECRET}
    access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
    refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REIDS_PORT}
      password: ${REDIS_PASSWORD}

env:
  secure-cookie: false

springdoc:
  api-docs:
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    # try it out 기능에 요청이 수행되는 소요시간을 표시
    display-request-duration: true
    # 문서를 로드할때 기본적으로 API가 모두 접힌 상태로 설정
    # list: 태그만 펼침, full: 모든 API 펼침
    doc-expansion: none
server:
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: '*'
