services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    networks:
      - ci-network

  promtail:
    image: grafana/promtail
    volumes:
      - ./logs:/logs
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - ci-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - ci-network